import { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    // Language
    chooseLanguage: "Choose Your Language",
    selectLanguage: "Select your preferred language to continue",
    english: "English",
    hindi: "Hindi",
    englishNative: "English",
    hindiNative: "हिंदी",
    continue: "Continue",
    languageNote:
      "Your language preference helps us provide you with the best experience.",

    // Role
    selectRole: "Select Your Role",
    roleSubtitle: "Choose how you want to use FarmBuddy",
    farmer: "Farmer",
    farmerDesc: "Book slots, manage produce & track bookings",
    operator: "Operator",
    operatorDesc: "Manage procurement, verification & queues",
    admin: "Admin",
    adminDesc: "Manage users, approvals & reports",
    secure: "Your data is secure with us",

    // Common
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    submit: "Submit",
    next: "Next",
    done: "Done",
    viewAll: "View All",

    // Farmer Login
    farmerLogin: "Farmer Login",
    welcomeFarmer: "Welcome, Farmer",
    kisanCode: "Kisan Code",
    mobileNumber: "Mobile Number",
    enterKisanCode: "Enter Kisan Code",
    enterMobile: "Enter mobile number",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    enterOtp: "Enter OTP",
    forgotKisanCode: "Forgot Kisan Code?",
    login: "Login",
    loginContinue: "Login to continue",
    invalidMobile: "Please enter a valid 10-digit mobile number.",
    otpInfo: "We'll send a secure OTP to your registered mobile number.",
    newToFarmBuddy: "New to FarmBuddy?",
    registration: "Register as Farmer",
    tagline: "Smart Procurement. Less Waiting.",

    // Dashboard
    hello: "Hello",
    todayOverview: "Today's Overview",
    upcomingBooking: "Upcoming Booking",
    bookingStatus: "Booking Status",
    bookNewSlot: "Book New Slot",
    quickAccess: "Quick Access",
    bookSlot: "Book Slot",
    myBooking: "My Booking",
    tokenQueue: "Token / Queue",
    payment: "Payment",
    profile: "Profile",
    notifications: "Notifications",
    history: "History",

    // Booking
    selectCrop: "Select Crop",
    selectCentre: "Select Procurement Centre",
    selectDate: "Select Date",
    availableSlots: "Available Time Slots",
    confirmBooking: "Confirm & Book Slot",
    bookingConfirmed: "Booking Confirmed",
    bookingId: "Booking ID",
    status: "Status",
    confirmed: "Confirmed",
    available: "Available",
    full: "Full",
    morning: "Morning",
    afternoon: "Afternoon",
    oneHour: "1 Hour",

    // Crops
    wheat: "Wheat",
    soybean: "Soybean",
    maize: "Maize",
    mustard: "Mustard",

    quintal: "Quintal",
    searchProcurementCentre: "Search procurement centre...",
    selectYourCrop: "Select your crop",
    selectProcurementCentre: "Select procurement centre",
    slotSelected: "Slot Selected",
    pleaseFillAllDetails: "Please fill all details",
    slotBookedSuccessfully: "Slot booked successfully!",
    scheduleProcurement: "Schedule your procurement",
    procurementCentre: "Procurement Centre",
    availableTimeSlots: "Available Time Slots",
    currentBooking: "Your current procurement booking",
    noBookingYet: "No Booking Yet",
    bookProcurementSlot: "Book a procurement slot to see it here.",
    date: "Date",
    time: "Time",
    bookingCentre: "Procurement Centre",
    tokenQueueTitle: "Token & Queue",
    tokenQueueSubtitle: "Your procurement queue status",
    noActiveBooking: "No Active Booking",
    bookSlotFirstToken: "Book a slot first to get your token number.",
    yourToken: "Your Token",
    currentQueuePosition: "Current Queue Position",
    slot: "Slot",
    reachCentreNote: "Please reach the procurement centre before your allotted slot. Your token will be processed according to the live queue.",
    bookingHistoryTitle: "Booking History",
    bookingHistorySubtitle: "Your procurement booking records",
    noBookingHistory: "No Booking History",
    pastBookingsNote: "Your completed and past bookings will appear here.",
    prototypeHistoryNote: "This prototype currently shows the latest booking. After backend integration, all previous bookings will be stored here.",
    paymentTitle: "Payment",
    paymentSubtitle: "Procurement payment status",
    noActivePayment: "No Active Booking",
    completeBookingPayment: "Complete a booking first to see its payment details.",
    paymentPending: "Payment Pending",
    procurementPayment: "Procurement Payment",
    paymentPendingNote: "Payment amount will be updated after procurement is completed.",
    bookingDetailsTitle: "Booking Details",
    paymentPrototypeNote: "Payment will be reflected here once the procurement transaction is processed. No amount is assumed in this prototype.",
    profileTitle: "My Profile",
    profileSubtitle: "Farmer account information",
    verifiedFarmer: "Verified Farmer",
    personalDetails: "Personal Details",
    fullName: "Full Name",
    farmerIdKisanCode: "Farmer ID / Kisan Code",
    fullAddress: "Full Address",
    village: "Village",
    post: "Post",
    tehsilBlock: "Tehsil / Block",
    district: "District",
    state: "State",
    pinCode: "PIN Code",
    farmDetails: "Farm Details",
    landArea: "Land Area",
    landUnit: "Land Unit",
    mainCrop: "Main Crop",
    bankDetails: "Bank Details",
    accountHolderName: "Account Holder Name",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    ifscCode: "IFSC Code",
    bankVerified: "Bank account verified",
    verification: "Verification",
    aadhaar: "Aadhaar",
    landRecord: "Land Record",
    farmerRegistration: "Farmer Registration",
    submittedVerified: "Submitted · Verified",
    accountInformation: "Account Information",
    registrationDate: "Registration Date",
    accountStatus: "Account Status",
    active: "Active",
    logout: "Logout",
    home: "Home",
    verified: "Verified",
    // Status
    upcoming: "Upcoming",
    completed: "Completed",
    cancelled: "Cancelled",
    inProcess: "In Process",
  },

  hi: {
    // Language
    chooseLanguage: "अपनी भाषा चुनें",
    selectLanguage: "जारी रखने के लिए अपनी पसंदीदा भाषा चुनें",
    english: "अंग्रेज़ी",
    hindi: "हिंदी",
    englishNative: "English",
    hindiNative: "हिंदी",
    continue: "जारी रखें",
    languageNote:
      "आपकी भाषा की पसंद हमें आपको बेहतर अनुभव देने में मदद करती है।",

    // Role
    selectRole: "अपनी भूमिका चुनें",
    roleSubtitle: "चुनें कि आप FarmBuddy का उपयोग कैसे करना चाहते हैं",
    farmer: "किसान",
    farmerDesc: "स्लॉट बुक करें, उपज प्रबंधित करें और बुकिंग देखें",
    operator: "ऑपरेटर",
    operatorDesc: "खरीद, सत्यापन और कतार प्रबंधित करें",
    admin: "एडमिन",
    adminDesc: "यूज़र, अनुमोदन और रिपोर्ट प्रबंधित करें",
    secure: "आपका डेटा हमारे साथ सुरक्षित है",

    // Common
    back: "वापस",
    save: "सेव करें",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    submit: "जमा करें",
    next: "आगे",
    done: "पूर्ण",
    viewAll: "सभी देखें",

    // Farmer Login
    farmerLogin: "किसान लॉगिन",
    welcomeFarmer: "स्वागत है, किसान",
    kisanCode: "किसान कोड",
    mobileNumber: "मोबाइल नंबर",
    enterKisanCode: "किसान कोड दर्ज करें",
    enterMobile: "मोबाइल नंबर दर्ज करें",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करें",
    enterOtp: "OTP दर्ज करें",
    forgotKisanCode: "किसान कोड भूल गए?",
    login: "लॉगिन",
    loginContinue: "जारी रखने के लिए लॉगिन करें",
    invalidMobile: "कृपया 10 अंकों का सही मोबाइल नंबर दर्ज करें।",
    otpInfo: "आपके पंजीकृत मोबाइल नंबर पर सुरक्षित OTP भेजा जाएगा।",
    newToFarmBuddy: "FarmBuddy पर नए हैं?",
    registration: "किसान के रूप में पंजीकरण करें",
    tagline: "स्मार्ट खरीद। कम इंतज़ार।",

    // Dashboard
    hello: "नमस्ते",
    todayOverview: "आज का विवरण",
    upcomingBooking: "आगामी बुकिंग",
    bookingStatus: "बुकिंग स्थिति",
    bookNewSlot: "नया स्लॉट बुक करें",
    quickAccess: "त्वरित विकल्प",
    bookSlot: "स्लॉट बुक करें",
    myBooking: "मेरी बुकिंग",
    tokenQueue: "टोकन / कतार",
    payment: "भुगतान",
    profile: "प्रोफ़ाइल",
    notifications: "सूचनाएँ",
    history: "इतिहास",

    // Booking
    selectCrop: "फसल चुनें",
    selectCentre: "खरीद केंद्र चुनें",
    selectDate: "तारीख चुनें",
    availableSlots: "उपलब्ध समय स्लॉट",
    confirmBooking: "पुष्टि करें और स्लॉट बुक करें",
    bookingConfirmed: "बुकिंग की पुष्टि हो गई",
    bookingId: "बुकिंग आईडी",
    status: "स्थिति",
    confirmed: "पुष्टि हुई",
    available: "उपलब्ध",
    full: "भर गया",
    morning: "सुबह",
    afternoon: "दोपहर",
    oneHour: "1 घंटा",

    // Crops
    wheat: "गेहूँ",
    soybean: "सोयाबीन",
    maize: "मक्का",
    mustard: "सरसों",

    quintal: "क्विंटल",
    searchProcurementCentre: "प्रोक्योरमेंट केंद्र खोजें...",
    selectYourCrop: "अपनी फसल चुनें",
    selectProcurementCentre: "प्रोक्योरमेंट केंद्र चुनें",
    slotSelected: "स्लॉट चुना गया",
    pleaseFillAllDetails: "कृपया सभी जानकारी भरें",
    slotBookedSuccessfully: "स्लॉट सफलतापूर्वक बुक हो गया!",
    scheduleProcurement: "अपना प्रोक्योरमेंट शेड्यूल करें",
    procurementCentre: "प्रोक्योरमेंट केंद्र",
    availableTimeSlots: "उपलब्ध समय स्लॉट",
    currentBooking: "आपकी वर्तमान प्रोक्योरमेंट बुकिंग",
    noBookingYet: "अभी कोई बुकिंग नहीं",
    bookProcurementSlot: "अपना प्रोक्योरमेंट स्लॉट बुक करने के लिए यहाँ जाएँ।",
    date: "तारीख",
    time: "समय",
    bookingCentre: "प्रोक्योरमेंट केंद्र",
    tokenQueueTitle: "टोकन और कतार",
    tokenQueueSubtitle: "आपकी प्रोक्योरमेंट कतार की स्थिति",
    noActiveBooking: "कोई सक्रिय बुकिंग नहीं",
    bookSlotFirstToken: "टोकन नंबर पाने के लिए पहले स्लॉट बुक करें।",
    yourToken: "आपका टोकन",
    currentQueuePosition: "वर्तमान कतार स्थिति",
    slot: "स्लॉट",
    reachCentreNote: "अपने निर्धारित स्लॉट से पहले प्रोक्योरमेंट केंद्र पहुँचें। आपका टोकन लाइव कतार के अनुसार संसाधित किया जाएगा।",
    bookingHistoryTitle: "बुकिंग इतिहास",
    bookingHistorySubtitle: "आपकी प्रोक्योरमेंट बुकिंग का रिकॉर्ड",
    noBookingHistory: "कोई बुकिंग इतिहास नहीं",
    pastBookingsNote: "आपकी पूरी और पिछली बुकिंग यहाँ दिखाई देंगी।",
    prototypeHistoryNote: "इस प्रोटोटाइप में अभी नवीनतम बुकिंग दिखाई जाती है। बैकएंड जुड़ने के बाद सभी पिछली बुकिंग यहाँ संग्रहीत होंगी।",
    paymentTitle: "भुगतान",
    paymentSubtitle: "प्रोक्योरमेंट भुगतान की स्थिति",
    noActivePayment: "कोई सक्रिय बुकिंग नहीं",
    completeBookingPayment: "भुगतान विवरण देखने के लिए पहले बुकिंग पूरी करें।",
    paymentPending: "भुगतान लंबित",
    procurementPayment: "प्रोक्योरमेंट भुगतान",
    paymentPendingNote: "प्रोक्योरमेंट पूरा होने के बाद भुगतान की राशि अपडेट की जाएगी।",
    bookingDetailsTitle: "बुकिंग विवरण",
    paymentPrototypeNote: "प्रोक्योरमेंट लेनदेन संसाधित होने के बाद भुगतान यहाँ दिखाई देगा। इस प्रोटोटाइप में कोई राशि मानकर नहीं चल रहे हैं।",
    profileTitle: "मेरी प्रोफ़ाइल",
    profileSubtitle: "किसान खाते की जानकारी",
    verifiedFarmer: "सत्यापित किसान",
    personalDetails: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    farmerIdKisanCode: "किसान आईडी / किसान कोड",
    fullAddress: "पूरा पता",
    village: "गाँव",
    post: "डाकघर",
    tehsilBlock: "तहसील / ब्लॉक",
    district: "जिला",
    state: "राज्य",
    pinCode: "पिन कोड",
    farmDetails: "खेत की जानकारी",
    landArea: "भूमि क्षेत्र",
    landUnit: "भूमि इकाई",
    mainCrop: "मुख्य फसल",
    bankDetails: "बैंक विवरण",
    accountHolderName: "खाता धारक का नाम",
    bankName: "बैंक का नाम",
    accountNumber: "खाता संख्या",
    ifscCode: "IFSC कोड",
    bankVerified: "बैंक खाता सत्यापित",
    verification: "सत्यापन",
    aadhaar: "आधार",
    landRecord: "भूमि रिकॉर्ड",
    farmerRegistration: "किसान पंजीकरण",
    submittedVerified: "जमा · सत्यापित",
    accountInformation: "खाता जानकारी",
    registrationDate: "पंजीकरण तिथि",
    accountStatus: "खाते की स्थिति",
    active: "सक्रिय",
    logout: "लॉगआउट",
    home: "होम",
    verified: "सत्यापित",
    // Status
    upcoming: "आगामी",
    completed: "पूर्ण",
    cancelled: "रद्द",
    inProcess: "प्रक्रिया में",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("bookagri-language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("bookagri-language", language);
  }, [language]);

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider
      value={{
        language,
        changeLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
